#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

polybar main &

if [[ $(xrandr -q | grep 'DisplayPort-1 connected') ]]; then
    xrandr --output eDP --primary --mode 2880x1920 --rotate normal --output DisplayPort-1 --mode 2560x1440 --rotate normal --right-of eDP
    polybar offset_monitor &
fi

bspc monitor eDP -d I II
bspc monitor DisplayPort-1 -d III IV

# bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop=^1 follow=off -o
bspc rule -a alacritty desktop=^2 follow=off -o
bspc rule -a Zathura state=tiled

firefox &

feh --bg-fill ~/Pictures/firewatch_bg_3.jpg
